### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by dmonzonis** [tonzo-studios/rogue-like#23]
Some classes don't have tests yet, and should be tested thoroughly (Entity, Behavior, etc).

**Comment by Elkasitu** [comment]
I think there's still some things that we haven't covered with tests yet, #36 helped but we're far from decent coverage, you could try implementing codecov and see where we're at, we should aim for 80% coverage even though having 70% is good enough.

**Comment by monzo94** [comment]
OK. I'll add tests for all the stuff I've done recently.
