### ISSUE TITLE
Make tiles occupied by a blocking entity non-walkable

### ISSUE THREAD

**Issue by monzo94** [tonzo-studios/rogue-like#27]
Instead of checking for blocking entities in movement logic, mark tiles occupied by blocking entities as non-walkable in the dungeon. This will also improve the pathfinding algorithm execution as an entity trying to move from A to B with another entity in its direct path will move around it, instead of trying to push it and never reaching B like it happens now.

**Comment by Elkasitu** [comment]
makes sense
