### ISSUE TITLE
Add Views

### ISSUE THREAD

**Issue by dmonzonis** [tonzo-studios/rogue-like#41]
Instead of rendering the entire map on the console, use views to draw only a portion of it. A view has a fixed size, which allows for maps with different sizes to exist without breaking the console, and also allows for zooming in/out and panning the view, so that the player can still see the entire map, no matter how big it may be.

**Comment by Elkasitu** [comment]
Do views come with TDL or would we have to implement this ourselves?

**Comment by monzo94** [comment]
We'd have to implement them ourselves.
