### ISSUE TITLE
Add display manager

### ISSUE THREAD

**Issue by monzo94** [tonzo-studios/rogue-like#9]
Add display manager class that should handle drawing stuff to the screen. Maybe refactor render functions into it too. Also implement entity drawing by giving entities a char and color attributes, which are passed to the display manager, since currently the code tries to use a nonexistent draw method from entity.

**Comment by Elkasitu** [comment]
As mentioned before, there probably needs to be an observer/observant design pattern for entity.move, I'll see if I can add it in a simplistic manner, ideally with @observer @observed decorators or something along those lines

**Comment by monzo94** [comment]
The way it's done now it just re-draws all visible entities each turn. The only thing it only renders when needed is the map layout. Given that there will probably never be more than 5 or 10 entities visible at a time, maybe it's not that useful to have an observer pattern here, since drawing a few entities each turn isn't that costly anyway. But it's your call.

**Comment by Elkasitu** [comment]
Ah ok then yeah, no need for the observer pattern then

**Comment by monzo94** [comment]
Done as of 775d6ea4f582cacb0148866a9d9c9303ac1964b5
